/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package streamingcatalogue;

import java.io.File;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.ObjectOutputStream;
import javax.swing.JOptionPane;

/**
 * Program Name: CatalogueGUI.java 
 * Date: 04/01/2021
 * @author E Feighery (x19413886)
 * @Reference: https://mymoodle.ncirl.ie/course/view.php?id=563/ (StudentApp (with FileI/O) in
 * the FileIO/Exception section in Object Oriented Programming)
 */
public class CatalogueGUI extends javax.swing.JFrame {

    // Declaring the variables from the other classes so that they can be used here.
    String title, genre, duration, cert;
    int seriesNo, episodeNo;

    // Here, I declare the Array of Objects that tha GUI application will be using to store all of the entries.
    Catalogue mediaList[];

    // I also declare a counter that will store how many entries are in the array mediaList.
    int capacity = 0;

    /**
     * Creates new form CatalogueGUI
     */
    public CatalogueGUI() {
        initComponents();

        // Here, I initialise the array and declare how many entries can be stored here; in this case 3 entries.
        mediaList = new Catalogue[3];

        // I then initialise the counter to be set to 0
        capacity = 0;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        applicationLbl = new javax.swing.JLabel();
        titleLbl = new javax.swing.JLabel();
        titleTF = new javax.swing.JTextField();
        genreLbl = new javax.swing.JLabel();
        genreTF = new javax.swing.JTextField();
        durationLbl = new javax.swing.JLabel();
        durationTF = new javax.swing.JTextField();
        certLbl = new javax.swing.JLabel();
        certTF = new javax.swing.JTextField();
        seriesNoLbl = new javax.swing.JLabel();
        seriesNoTF = new javax.swing.JTextField();
        episodeNoLbl = new javax.swing.JLabel();
        episodeNoTF = new javax.swing.JTextField();
        addBtn = new javax.swing.JButton();
        displayBtn = new javax.swing.JButton();
        saveBtn = new javax.swing.JButton();
        deleteBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        applicationLbl.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        applicationLbl.setForeground(new java.awt.Color(0, 0, 255));
        applicationLbl.setText("My Streaming Catalogue Application");

        titleLbl.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        titleLbl.setText("Insert Title: ");

        titleTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                titleTFActionPerformed(evt);
            }
        });

        genreLbl.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        genreLbl.setText("Insert Genre: ");

        genreTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                genreTFActionPerformed(evt);
            }
        });

        durationLbl.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        durationLbl.setText("Insert Run-Time: ");

        durationTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                durationTFActionPerformed(evt);
            }
        });

        certLbl.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        certLbl.setText("Insert Age Rating: ");

        certTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                certTFActionPerformed(evt);
            }
        });

        seriesNoLbl.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        seriesNoLbl.setText("Insert Series Number: ");

        seriesNoTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seriesNoTFActionPerformed(evt);
            }
        });

        episodeNoLbl.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        episodeNoLbl.setText("Insert Episode Number: ");

        episodeNoTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                episodeNoTFActionPerformed(evt);
            }
        });

        addBtn.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        addBtn.setForeground(new java.awt.Color(204, 0, 0));
        addBtn.setText("Add Entry");
        addBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addBtnActionPerformed(evt);
            }
        });

        displayBtn.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        displayBtn.setForeground(new java.awt.Color(204, 0, 0));
        displayBtn.setText("Display Entries");
        displayBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                displayBtnActionPerformed(evt);
            }
        });

        saveBtn.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        saveBtn.setForeground(new java.awt.Color(204, 0, 0));
        saveBtn.setText("Save Entries to File");
        saveBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveBtnActionPerformed(evt);
            }
        });

        deleteBtn.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        deleteBtn.setForeground(new java.awt.Color(204, 0, 0));
        deleteBtn.setText("Delete Item 1");
        deleteBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(96, 96, 96)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(certLbl)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(certTF, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(seriesNoLbl)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(seriesNoTF, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(durationLbl)
                                    .addComponent(genreLbl)
                                    .addComponent(titleLbl))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(genreTF)
                                    .addComponent(durationTF, javax.swing.GroupLayout.DEFAULT_SIZE, 267, Short.MAX_VALUE)
                                    .addComponent(titleTF, javax.swing.GroupLayout.Alignment.TRAILING)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(applicationLbl)
                                .addGap(38, 38, 38))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(episodeNoLbl)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(59, 59, 59)
                                        .addComponent(episodeNoTF, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(deleteBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(displayBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addGap(49, 49, 49))))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(181, 181, 181)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(saveBtn)
                            .addComponent(addBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(123, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(applicationLbl)
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(titleLbl)
                    .addComponent(titleTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(47, 47, 47)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(genreTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(genreLbl))
                .addGap(47, 47, 47)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(durationTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(durationLbl))
                .addGap(47, 47, 47)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(certTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(certLbl))
                .addGap(47, 47, 47)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(seriesNoTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(seriesNoLbl))
                .addGap(47, 47, 47)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(episodeNoTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(episodeNoLbl))
                .addGap(85, 85, 85)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(displayBtn)
                    .addComponent(addBtn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 46, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(saveBtn)
                    .addComponent(deleteBtn))
                .addGap(79, 79, 79))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void titleTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_titleTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_titleTFActionPerformed

    private void genreTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_genreTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_genreTFActionPerformed

    private void durationTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_durationTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_durationTFActionPerformed

    private void certTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_certTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_certTFActionPerformed

    private void seriesNoTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seriesNoTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_seriesNoTFActionPerformed

    private void episodeNoTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_episodeNoTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_episodeNoTFActionPerformed

    private void addBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addBtnActionPerformed
        // TODO add your handling code here:

        // An object of the Movies instantiable class is created and declared
        Movies md = new Movies();

        // The md object then grabs the inputs from the following text fields 
        md.setTitle(titleTF.getText());
        md.setGenre(genreTF.getText());
        md.setDuration(durationTF.getText());
        md.setCert(certTF.getText());

        // The ArrayOfObjects will keep the entry made inside itself, while the counter increments by one each time.
        mediaList[capacity] = md;
        capacity++;

        // An object of the TVShows instantiable class is created and declared as well
        TVShows tv = new TVShows();

        // The tv object then grabs the inputs from the following text fields 
        tv.setTitle(titleTF.getText());
        tv.setGenre(genreTF.getText());
        tv.setDuration(durationTF.getText());
        tv.setSeriesNo(Integer.parseInt(seriesNoTF.getText()));
        tv.setEpisodeNo(Integer.parseInt(episodeNoTF.getText()));

        // The ArrayOfObjects will keep the entry made inside itself, while the counter increments by one each time.
        mediaList[capacity] = tv;
        capacity++;


    }//GEN-LAST:event_addBtnActionPerformed

    private void displayBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_displayBtnActionPerformed
        // TODO add your handling code here:

        // A for loop will cycle through the counter and the array
        for (int i = 0; i < capacity; i++) {

            // An object of the array is declared for displaying the data
            Catalogue cd = mediaList[i];

            // If certain content in the array is an instance of the Movies class, that content of data will be displayed to the user in a message window
            if (cd instanceof Movies) {
                JOptionPane.showMessageDialog(null, "Title: " + cd.getTitle() + ", Genre: " + cd.getGenre() + ", Duration (in minutes): " + cd.getDuration() + ", Age Rating: " + cd.getCert());
            } // Likewise, if certain content inside the array is an instance of the TVShows class, that content of data will be displayed to the user in a message window
            else if (cd instanceof TVShows) {
                JOptionPane.showMessageDialog(null, "Title: " + cd.getTitle() + ", Genre: " + cd.getGenre() + ", Duration (in minutes): " + cd.getDuration() + ", Series number: " + ((TVShows) cd).getSeriesNo() + ", Episode Number: " + ((TVShows) cd).getEpisodeNo());
            }
        }
    }//GEN-LAST:event_displayBtnActionPerformed

    private void saveBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveBtnActionPerformed
        // TODO add your handling code here:

        // @Reference: https://mymoodle.ncirl.ie/course/view.php?id=563/ (StudentApp (with FileI/O) in the FileIO/Exception section in Object Oriented Programming)
        
        // Since I am creating a file with the inserted data, I created the following variables.
        File newFile; // For creating the file that will be created with the inputted data.
        FileOutputStream fStreams; // To help write and output the file.
        ObjectOutputStream oStreams; // Takes the lines and character data to write the data in the file.

// Since the save action can run into an error, a try-catch method to check for any errors that happened.
        try {
            newFile = new File("Info.data");
            fStreams = new FileOutputStream(newFile);
            oStreams = new ObjectOutputStream(fStreams);

            // An object of the array will be written by the Object Stream 
            oStreams.writeObject(mediaList);

            // Once it's done, the action will close.
            oStreams.close();
        } // If the application runs into an error, a message about it will be displayed
        catch (IOException exe) {
            JOptionPane.showMessageDialog(null, "The system had an error while saving: " + exe);
        }
    }//GEN-LAST:event_saveBtnActionPerformed

    private void deleteBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteBtnActionPerformed
        // TODO add your handling code here:

        // A for loop will cycle through the counter to find the first item in the array.
        for (int i = 0; i < capacity; i++) {

            // Here the object of the Catalogue class equals to index 0 of the array (In Java, the number one is 0).
            Catalogue cd = mediaList[0];

            // Removes the entry's data contents if the title is the first in the array.
            if (cd.getTitle().equalsIgnoreCase(titleTF.getText())) {

                // Once it finds the first entry, the array takes out the index 0 (The first entry in the array) while the counter is decremented (subtract by 1).
                mediaList[0] = mediaList[capacity - 1];
                capacity--;

                JOptionPane.showMessageDialog(null, "Item " + titleTF.getText() + " has been removed from the array");
            }
        }
    }//GEN-LAST:event_deleteBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CatalogueGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CatalogueGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CatalogueGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CatalogueGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CatalogueGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addBtn;
    private javax.swing.JLabel applicationLbl;
    private javax.swing.JLabel certLbl;
    private javax.swing.JTextField certTF;
    private javax.swing.JButton deleteBtn;
    private javax.swing.JButton displayBtn;
    private javax.swing.JLabel durationLbl;
    private javax.swing.JTextField durationTF;
    private javax.swing.JLabel episodeNoLbl;
    private javax.swing.JTextField episodeNoTF;
    private javax.swing.JLabel genreLbl;
    private javax.swing.JTextField genreTF;
    private javax.swing.JButton saveBtn;
    private javax.swing.JLabel seriesNoLbl;
    private javax.swing.JTextField seriesNoTF;
    private javax.swing.JLabel titleLbl;
    private javax.swing.JTextField titleTF;
    // End of variables declaration//GEN-END:variables
}
